
# Paths are relative to Top-Src-Dir. Duh.
INCLUDE( cmake/Qt4.cmake )

# Common stuff:

MACRO( _ADD_NOCASTS )
	ADD_DEFINITIONS(
		-DQT_NO_CAST_FROM_ASCII
		-DQT_NO_CAST_TO_ASCII
		-DQT_NO_CAST_FROM_BYTEARRAY
	)
ENDMACRO()

MACRO( ADD_QT_LIBRARY _target )

	ADD_LIBRARY( ${_target} ${ARGN} )
	TARGET_LINK_LIBRARIES( ${_target} ${QT_LIBRARIES} )
	_ADD_NOCASTS()

ENDMACRO( ADD_QT_LIBRARY )

MACRO( ADD_QT_EXECUTABLE _target )

	ADD_EXECUTABLE( ${_target} ${ARGN} )
	TARGET_LINK_LIBRARIES( ${_target} ${QT_LIBRARIES} )
	_ADD_NOCASTS()

ENDMACRO( ADD_QT_EXECUTABLE )
