
IF( UNIX )

    MACRO( GCC_ADD_FLAG _flag )

        IF( NOT DEFINED CMAKE_CXX_FLAGS )
            SET( CMAKE_CXX_FLAGS "${_flag}" CACHE STRING "C++ Build Flags" FORCE )
        ENDIF()

        IF( NOT "${CMAKE_CXX_FLAGS}" MATCHES ".*${_flag}.*" )
            SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${_flag}" CACHE STRING "C++ Build Flags" FORCE )
        ENDIF()

    ENDMACRO()

ENDIF()

MACRO( SET_OUTPUT_PATHS )
    SET( EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin )
    SET( LIBRARY_OUTPUT_PATH    ${CMAKE_BINARY_DIR}/bin )
ENDMACRO()
